server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5431/tech_store}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "8aec10e5079dea67efc958810f4331ff586886cccf3abb60a66fb6e31b3c97d4"
  refresh_secret: "c4cca68d1ae4bf193ca5ee59649e92d5ffe3be74de24939373a72f0d6914f7f0"
  valid_duration: 40
  refresh_duration: 72000

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dnniedh2d}
  api-key: ${CLOUDINARY_API_KEY:821269299376188}
  api-secret: ${CLOUDINARY_API_SECRET:AF-gW8iwLA57Ssqpf7D0uY9bu0c}