server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/techstore
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "8aec10e5079dea67efc958810f4331ff586886cccf3abb60a66fb6e31b3c97d4"