server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/techstore
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1b6a40d0e97e2ed62e548fdf7a6146462782172bbc82ca1058e901755e4793f"