name: techstore
services:
  postgres:
    image: postgres:16-alpine
    container_name: techstore-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  # techstore-backend:
  #   image: techstore-backend:1.0.0
  #   container_name: techstore-backend
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/techstore
  #     SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
  #     SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
  #     CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
  #     CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
  #     CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres

volumes:
  pgdata:
